<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGkciq15\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGkciq15/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGkciq15.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGkciq15\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGkciq15\appProdProjectContainer([
    'container.build_hash' => 'Gkciq15',
    'container.build_id' => 'fa0deb6f',
    'container.build_time' => 1760283942,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGkciq15');
